dtb-$(CONFIG_ARCH_MSM8994) += huawei_lunch_box_va.dtb \
                              huawei_angler_v1.dtb \
                              huawei_angler_v2.dtb \
                              huawei_angler_v3.dtb \
                              huawei_angler_v4.dtb \
                              huawei_angler_vn1.dtb \
                              huawei_angler_vn2.dtb \
                              huawei_angler_row_v1.dtb \
                              huawei_angler_row_v3.dtb \
                              huawei_angler_row_vn1.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb

